### ISSUE TITLE
Is it possible to add support for download GitHub build artifacts from actions

### ISSUE THREAD

**Issue by Josh65-2201** [NewAmazingPVP/AutoUpdatePlugins#12]
I want to have grim (https://github.com/GrimAnticheat/Grim) auto update since it get many updates a day but they do there release via the GitHub actions artifact rather then release page. Is it possible to add support for them?

**Comment by NewAmazingPVP** [comment]
Sorry for not replying @Josh65-2201. I have added the feature of downloading github build artifacts from actions, so please try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1257829214242209792/autoupdateplugins-devFix.jar?ex=6685d43e&is=668482be&hm=649bb7f05ef7d602a8b67bf6a42e20bb6cfcb62374f5b245a4ea686412575b4b&) out. For example, you can try this link: https://github.com/Elytrium/LimboAPI/dev to download that plugin's actions (just add /dev at the end to be able to differentiate between releases and actions). About Grimanticheat, they do not allow you to download their actions without a github personal token, so I am afraid that I don't know how to deal with that situation. https://[api.github.com/repos/GrimAnticheat/Grim/actions/artifacts] (https://api.github.com/repos/GrimAnticheat/Grim/actions/artifacts) https://[api.github.com/repos/GrimAnticheat/Grim/actions/artifacts/1661144786/zip]![image](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/87737759/857fb6ce-1fff-4bb5-a20c-6efd849a6e95)(https://api.github.com/repos/GrimAnticheat/Grim/actions/artifacts/1661144786/zip)

**Comment by Josh65-2201** [comment]
It alright thanks for adding it. As for the token, would it not be possible for me to provide one and add it to the config for the plugin to use?

**Comment by Josh65-2201** [comment]
I have found that they release updates less often then I thought and are also uploaded to hanger, so the issue for me is solved. Thanks for the work helping me.

**Comment by NewAmazingPVP** [comment]
Great to hear!

**Comment by NewAmazingPVP** [comment]
@Josh65-2201 By the way, I am aware that for GrimAC, you found that they upload frequently on Hangar, but for other plugins with github actions, I have finally added a feature where you can put in your github personal access token in the config and it will let you download builds from actions. Here is the [build]: https://cdn.discordapp.com/attachments/1103725182314614834/1259548473737351239/autoupdateplugins-1.0.jar?ex=668c156d&is=668ac3ed&hm=b8dfbdfc112fd6d167c86aaf8dcf20e70726b2a17aa0209ee948087ca297bfca Make sure to regenerate the configuration if you need to test it out or so. [Here is how you can get your personal access token] (https://www.geeksforgeeks.org/how-to-generate-personal-access-token-in-github/). And you only need to give it public_repo permissions to make it work. ![image](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/87737759/13b9ad20-53a4-40fe-8678-93cd8bf4026b)

**Comment by Josh65-2201** [comment]
Great, thanks for making it.
