### ISSUE TITLE
Doesn't update geyser correct anymore

### ISSUE THREAD

**Issue by Josh65-2201** [NewAmazingPVP/AutoUpdatePlugins#13]
Using this download link in the config https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
It shows as the same for geyser spigot/paper download. The plugin when using `/update` says it downloads it with no other errors but geyser version report it outdated.

I'm using the build linked in my previous issue https://github.com/NewAmazingPVP/AutoUpdatePlugins/issues/12#issuecomment-2212506283

**Comment by NewAmazingPVP** [comment]
Hey @Josh65-2201 try this build out, I have noticed that my implementation to access GitHub workflow/actions is slightly flawed and causes issues like this, so I have disabled that feature until I can fix it. Please try this [build out](https://cdn.discordapp.com/attachments/1103725182314614834/1260790235860570132/autoupdateplugins-1.0.jar?ex=669099e8&is=668f4868&hm=0994ed0ac6b09ac4031ac0884216bed8b607a2b00a5abfe959d7985897b19f71&)

**Comment by NewAmazingPVP** [comment]
Actually, nevermind, it seems like it was a small issue and there was no need to disable Github actions support. I re-added it, so I would appreciate it if you could test this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1260791565857591377/autoupdateplugins-1.0.jar?ex=66909b25&is=668f49a5&hm=d5d10485438b6b71c5641fe60098abd63c575386a309055927197b5d27589b90&)

**Comment by Josh65-2201** [comment]
Sure, I will says when geyser has an update available.

**Comment by NewAmazingPVP** [comment]
Sure, please try the new version and let me know. If it still persists, reopen this issue.

**Comment by Josh65-2201** [comment]
Geyser still doesn't update

**Comment by NewAmazingPVP** [comment]
@Josh65-2201 What's your bootTime in config.yml? Try setting it to something higher, like 250.

**Comment by Josh65-2201** [comment]
I have them both set to 99999. I use the update command before a server restart. I know it downloaded too because it's the first one on the list of 4.

**Comment by NewAmazingPVP** [comment]
@Josh65-2201 It seems to be downloading the latest geyser for me on a plain new server, could you try on a different server with no plugins? 
![image](https://github.com/user-attachments/assets/df2c0c29-c683-477a-982d-0364d4ffd4b2)
![image](https://github.com/user-attachments/assets/c330a23b-4bf3-4d81-9e76-09a2531f93f1)

**Comment by NewAmazingPVP** [comment]
Use the newest released version, and make sure to check that there isn't another geyser jar in plugins.

**Comment by Josh65-2201** [comment]
It's working with v9. I saw that it was downloading as .zip rather then .jar before so it wasn't replace the existing file.

**Comment by NewAmazingPVP** [comment]
Yes, that was the bug fixed with v9.0.
