### ISSUE TITLE
Citizens Jenkins doesnt work

### ISSUE THREAD

**Issue by RyuguDev** [NewAmazingPVP/AutoUpdatePlugins#14]
[17:29:03 INFO]: [AutoUpdatePlugins] [STDOUT] Failed to download plugin from jenkins, https://ci.citizensnpcs.co/job/Citizens2/lastBuild/ , are you sure link is correct and in right format?https://ci.citizensnpcs.co/job/Citizens2/lastBuild/lastSuccessfulBuild/api/json

**Comment by NewAmazingPVP** [comment]
Hey @RyuguDev, try putting in this link https://ci.citizensnpcs.co/job/Citizens2/ instead of https://ci.citizensnpcs.co/job/Citizens2/lastBuild/

**Comment by RyuguDev** [comment]
[08:05:21 INFO]: [AutoUpdatePlugins] [STDOUT] Citizens ---- https://ci.citizensnpcs.co/job/Citizens2/
[08:05:22 INFO]: [AutoUpdatePlugins] [STDOUT] Failed to download plugin from jenkins, https://ci.citizensnpcs.co/job/Citizens2/ , are you sure link is correct and in right format?https://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/api/json

**Comment by NewAmazingPVP** [comment]
Hey @RyuguDev, I see what you are talking about now. So, it looks like the citizens Jenkins is structured differently than most other Ci Jenkins builds of other plugins; therefore, simply putting that link won't work. However, most other Jenkins of other plugins should work fine, such as Essentials, Authmereloaded, Luckperms, etc.. I will try to see if I can implement something for citizens in my free time, but I am not quite sure.

**Comment by NewAmazingPVP** [comment]
(TODO) Also add support for protocollib jenkins

**Comment by NewAmazingPVP** [comment]
@RyuguDev Sorry for taking so long, try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1311746187342123089/autoupdateplugins-betterJenkins.jar?ex=6749fa56&is=6748a8d6&hm=d44a652dc92ea5d86a9946b561062c3aa957d9de0e822b9537666771ad861203&) out and let me know if it works as intended!

**Comment by NewAmazingPVP** [comment]
Almost all jenkins should work now.

**Comment by RyuguDev** [comment]
Thanks, the build you Provided isnt downloadable btw. And: polymart isnt working too and the offical polymart Updater is overriding your plugin

**Comment by NewAmazingPVP** [comment]
Hey there, I have released the [new version](https://github.com/NewAmazingPVP/AutoUpdatePlugins/releases/download/v10.5/autoupdateplugins-10.5.jar) with this feature implemented. Please let me know if any issues arise. 

Also, you are right about Polymart, there is currently no support for it, partly because there already exists the [Polymart updater](https://polymart.org/resource/polymart-plugin.323) as you mentioned. However, I might consider adding support for it in the future!
