### ISSUE TITLE
Another Build Server Providers wich arent working

### ISSUE THREAD

**Issue by RyuguDev** [NewAmazingPVP/AutoUpdatePlugins#15]
https://blob.build/
https://thebusybiscuit.github.io/builds/

**Comment by NewAmazingPVP** [comment]
@RyuguDev Sure I can add support for these build servers. They do not work currently since they are not supported yet.

**Comment by NewAmazingPVP** [comment]
@RyuguDev Added the support for the build servers. Try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1299561172218941480/autoupdateplugins-newBuildServerSupport.jar?ex=671da628&is=671c54a8&hm=5f4072a5e6d420e4c63dee911381ba9c52cfaa186d1fbac8b968b5b032832e01&) and let me know if it works as intended. For example, try putting this link in list.yml

```yml
SlimeFun: https://blob.build/projects/Slimefun4/Dev
```

**Comment by NewAmazingPVP** [comment]
@RyuguDev Added this feature in the new release! Please let me know how it goes.
