### ISSUE TITLE
Add a command to run the update list

### ISSUE THREAD

**Issue by Josh65-2201** [NewAmazingPVP/AutoUpdatePlugins#5]
Add a command to run the auto update list as I have another plugin allowing me to run commands and restart the server for a constent update schedule.

**Comment by NewAmazingPVP** [comment]
Alright doesn't seem too hard I can add

**Comment by NewAmazingPVP** [comment]
Should be added with the latest release. Please go test it out since I haven't tested yet.

**Comment by Josh65-2201** [comment]
It works as expected for me

**Comment by NewAmazingPVP** [comment]
Alright perfect
