### ISSUE TITLE
Error downloading Spiget

### ISSUE THREAD

**Issue by SkyKingPX** [NewAmazingPVP/AutoUpdatePlugins#8]
Hello,
every time I start my server and the Plugin tries to download the Plugins this error shows up (only one time).
![image](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/95442431/057bfd44-774f-41bb-9dd3-2ed871122c6f)

I don't know if another Plugin causes this, so here are my plugins and my list.yml (converted into txt because of github):
[list.txt](https://github.com/NewAmazingPVP/AutoUpdatePlugins/files/13875807/list.txt)
![Screenshot 2024-01-09 164751](https://github.com/NewAmazingPVP/AutoUpdatePlugins/assets/95442431/c8651143-8e4c-48cd-9cdf-863f6c93cb0c)

**Comment by NewAmazingPVP** [comment]
In your console error log could you show me the plugin it tried downloading before the error happened? Looks like it's the headdrops plugin but I want to be sure

**Comment by SkyKingPX** [comment]
Yes it’s HeadDrop @NewAmazingPVP

**Comment by NewAmazingPVP** [comment]
@SkyKingPX try putting in this link
https://www.spigotmc.org/resources/%E2%9C%85-headdrop-free-1-16-1-20-fully-customizable.99976/

instead of https://www.spigotmc.org/resources/99976/

**Comment by SkyKingPX** [comment]
Yes, works now. Thanks and this is a great plugin!

**Comment by NewAmazingPVP** [comment]
Great! The problem was the regex pattern extracting the plugin ID from the link. Currently, it looks for something like this ".123/" but since you used the normal resources link, it couldn't find a dot followed by numbers and slash. I am probably going to release next version which will fix this, thus making it simpler to use the plugin.

**Comment by NewAmazingPVP** [comment]
Also @SkyKingPX I just released the new version https://github.com/NewAmazingPVP/AutoUpdatePlugins/releases/download/v6.5/autoupdateplugins-6.5.jar

With this version it won't matter if you use https://www.spigotmc.org/resources/99976/ or https://www.spigotmc.org/resources/%E2%9C%85-headdrop-free-1-16-1-20-fully-customizable.99976/ both links will work

Also, I have taken your suggestion into consideration and have long thought so doing separate loggers for all platforms but just don't have the time to recode, but I'll try if I do get time.

**Comment by NewAmazingPVP** [comment]
The logger thing is not an error though the plugin should work fine as it is. It's just not the most preferred way to log/send messages, therefore it's saying that.

**Comment by SkyKingPX** [comment]
I know.

But why is the plugin Version 6.5 instead of 6.1???

**Comment by SkyKingPX** [comment]
Ok.

But a better way would be for example:
1.0
1.1
1.2
1.2.1

**Comment by NewAmazingPVP** [comment]
Yeah I agree
